flowchart LR
    None[None]
    3[3]
    https___sibelco_sharepoint_com_sites_elektrischedienst_Shared_Documents_Automatisering_Automation_Public_Sequenties_Dessel_Sequentie_M4_Hoofdsequentie_M4_vsdx["https://sibelco.sharepoint.com/sites/elektrischedienst/Shared Documents/Automatisering/Automation Public/Sequenties/Dessel/Sequentie M4 Hoofdsequentie M4.vsdx"]
    16[16]
    1234[1234]
    Start_M4_30["Start M4_30"]
    1234_20[1234]
    Wis_keuze_uit_menu["Wis keuze uit menu"]
    M4_30_draait["M4_30 draait"]
    1234_24[1234]
    Geen_voorwaarde["Geen voorwaarde"]
    Open_M4_SVA_03_en_M4_SVA_04["Open M4_SVA_03 en M4_SVA_04"]
    1234_28[1234]
    Stop_M5_34__M5_34B__M5_33__M5_31B__M5_32__M5_30__M5_30L_AV__M5_30R_AV__M5_29__M5_28__M5_26__M5_25_M5_24__M5_23__M5_22__M5_21__M5_19__M5_18__M5_17__M5_16__M5_15Sluit_M5_55__M5_50__M5_11B__M5_11C["Stop M5_34, M5_34B, M5_33, M5_31B, M5_32, M5_30, M5_30L_AV, M5_30R_AV, M5_29, M5_28, M5_26, M5_25,M5_24, M5_23, M5_22, M5_21, M5_19, M5_18, M5_17, M5_16, M5_15Sluit M5_55, M5_50, M5_11B, M5_11C"]
    M4_SVA_03_en_M4_SVA_04_zijn_open["M4_SVA_03 en M4_SVA_04 zijn open"]
    1234_32[1234]
    M5_50_en_M5_55_zijn_gesloten__of_wacht_8_sec__["M5_50 en M5_55 zijn gesloten (of wacht 8 sec.)"]
    Start_M4_33["Start M4_33"]
    1234_36[1234]
    Stop_M5_14__M5_13__M5_12__M5_49__M5_48__M5_7__M5_6__M5_5__M5_38__M5_58__M5RV401Sluit_M5_43__M5_11A["Stop M5_14, M5_13, M5_12, M5_49, M5_48, M5_7, M5_6, M5_5, M5_38, M5_58, M5RV401Sluit M5_43, M5_11A"]
    M4_33_draait["M4_33 draait"]
    1234_40[1234]
    M5_43_is_gesloten__of_wacht_4_sec__["M5_43 is gesloten (of wacht 4 sec.)"]
    Start_M4_34A["Start M4_34A"]
    1234_44[1234]
    Stop_M5_46__M5_45__M5_47__M5_44["Stop M5_46, M5_45, M5_47, M5_44"]
    M4_34A_draait["M4_34A draait"]
    1234_48[1234]
    Wacht_4_sec_["Wacht 4 sec."]
    Start_M4_34B["Start M4_34B"]
    1234_52[1234]
    Stop_M5FA401__M5FA401FA__M5FA402["Stop M5FA401, M5FA401FA, M5FA402"]
    M4_34B_draait["M4_34B draait"]
    1234_56[1234]
    Wacht_10_sec_["Wacht 10 sec."]
    Start_M4_35["Start M4_35"]
    1234_60[1234]
    Sluit_M5SVA401["Sluit M5SVA401"]
    M4_35_draait["M4_35 draait"]
    1234_64[1234]
    M5SVA401_is_gesloten["M5SVA401 is gesloten"]
    Start_M4_36["Start M4_36"]
    1234_68[1234]
    Stop_M5RS401__M5RV402__M5_16__M5_15__M5BE401__M5FI401Sluit_M5SVA431__M5SVA432["Stop M5RS401, M5RV402, M5_16, M5_15, M5BE401, M5FI401Sluit M5SVA431, M5SVA432"]
    M4_36_draait["M4_36 draait"]
    1234_72[1234]
    M5SVA431_is_gesloten__of_wacht_15_sec__["M5SVA431 is gesloten (of wacht 15 sec.)"]
    Start_M4_TOIC1__tonnage__regeling_weegband_["Start M4_TOIC1 (tonnage- regeling weegband)"]
    1234_76[1234]
    Stop_M5BE401__M5_4["Stop M5BE401, M5_4"]
    Geen_voorwaarde_78["Geen voorwaarde"]
    1234_80[1234]
    Wacht_2_minuten["Wacht 2 minuten"]
    Productiestap[Productiestap]
    1234_84[1234]
    Reset_sequentie["Reset sequentie"]
    Start_M4_29["Start M4_29"]
    Voorwaarde[Voorwaarde]
    89[89]
    M4_29_draait["M4_29 draait"]
    Stap[Stap]
    1234_93[1234]
    Sluit_M4_SVA_05["Sluit M4_SVA_05"]
    Voorwaarde_96[Voorwaarde]
    1234_97[1234]
    M4_SVA_05_is_gesloten["M4_SVA_05 is gesloten"]
    Stap_100[Stap]
    1234_101[1234]
    Start_M4_32_2_of_M4_32_3__Oliepomp_["Start M4_32_2 of M4_32_3 (Oliepomp)"]
    104[104]
    1234_105[1234]
    106[106]
    Stap_108[Stap]
    1234_109[1234]
    Start_M4_32_6__koeling_["Start M4_32_6 (koeling)"]
    Voorwaarde_112[Voorwaarde]
    1234_113[1234]
    M4_32_6_draait["M4_32_6 draait"]
    Voorwaarde_116[Voorwaarde]
    Stap_117[Stap]
    1234_118[1234]
    Stap_120[Stap]
    Voorwaarde_121[Voorwaarde]
    1234_122[1234]
    Voorwaarde_124[Voorwaarde]
    Stap_125[Stap]
    1234_126[1234]
    Stap_128[Stap]
    Voorwaarde_129[Voorwaarde]
    1234_130[1234]
    Voorwaarde_132[Voorwaarde]
    Stap_133[Stap]
    1234_134[1234]
    Voorwaarde_136[Voorwaarde]
    Voorwaarde_137[Voorwaarde]
    1234_138[1234]
    Stap_140[Stap]
    Stap_141[Stap]
    1234_142[1234]
    Voorwaarde_144[Voorwaarde]
    Voorwaarde_145[Voorwaarde]
    1234_146[1234]
    Stap_148[Stap]
    Stap_149[Stap]
    1234_150[1234]
    Voorwaarde_152[Voorwaarde]
    Voorwaarde_153[Voorwaarde]
    1234_154[1234]
    Stap_156[Stap]
    Stap_157[Stap]
    1234_158[1234]
    Voorwaarde_160[Voorwaarde]
    Voorwaarde_161[Voorwaarde]
    1234_162[1234]
    Stap_164[Stap]
    Stap_165[Stap]
    1234_166[1234]
    Voorwaarde_168[Voorwaarde]
    Voorwaarde_169[Voorwaarde]
    1234_170[1234]
    Voorwaarde_172[Voorwaarde]
    Stap_173[Stap]
    1234_174[1234]
    Stap_176[Stap]
    Voorwaarde_177[Voorwaarde]
    1234_178[1234]
    Voorwaarde_180[Voorwaarde]
    Stap_181[Stap]
    1234_182[1234]
    Stap_184[Stap]
    Voorwaarde_185[Voorwaarde]
    1234_186[1234]
    Voorwaarde_188[Voorwaarde]
    Stap_189[Stap]
    1234_190[1234]
    Stap_192[Stap]
    Voorwaarde_193[Voorwaarde]
    1234_194[1234]
    Voorwaarde_196[Voorwaarde]
    Stap_197[Stap]
    1234_198[1234]
    Stap_200[Stap]
    Voorwaarde_201[Voorwaarde]
    655a[655a]
    Voorwaarde_204[Voorwaarde]
    Voorwaarde_205[Voorwaarde]
    655b[655b]
    Stap_208[Stap]
    Stap_209[Stap]
    1234_210[1234]
    Voorwaarde_212[Voorwaarde]
    Voorwaarde_213[Voorwaarde]
    1234_214[1234]
    Stap_216[Stap]
    Stap_217[Stap]
    1234_218[1234]
    Voorwaarde_220[Voorwaarde]
    Voorwaarde_221[Voorwaarde]
    1234_222[1234]
    Stap_224[Stap]
    Stap_225[Stap]
    1234_226[1234]
    Voorwaarde_228[Voorwaarde]
    Voorwaarde_229[Voorwaarde]
    1234_230[1234]
    Stap_232[Stap]
    Stap_233[Stap]
    1234_234[1234]
    Voorwaarde_236[Voorwaarde]
    Voorwaarde_237[Voorwaarde]
    1234_238[1234]
    Stap_240[Stap]
    Stap_241[Stap]
    1234_242[1234]
    Voorwaarde_244[Voorwaarde]
    Voorwaarde_245[Voorwaarde]
    1234_246[1234]
    Stap_248[Stap]
    Stap_249[Stap]
    1234_250[1234]
    Voorwaarde_252[Voorwaarde]
    Voorwaarde_253[Voorwaarde]
    1234_254[1234]
    Stap_256[Stap]
    Stap_257[Stap]
    1234_258[1234]
    Voorwaarde_260[Voorwaarde]
    Voorwaarde_261[Voorwaarde]
    1234_262[1234]
    Stap_264[Stap]
    Stap_265[Stap]
    1234_266[1234]
    Voorwaarde_268[Voorwaarde]
    Voorwaarde_269[Voorwaarde]
    1234_270[1234]
    Stap_272[Stap]
    Stap_273[Stap]
    1234_274[1234]
    Voorwaarde_276[Voorwaarde]
    Voorwaarde_277[Voorwaarde]
    1234_278[1234]
    Stap_280[Stap]
    Stap_281[Stap]
    1234_282[1234]
    Voorwaarde_284[Voorwaarde]
    Voorwaarde_285[Voorwaarde]
    1234_286[1234]
    Voorwaarde_288[Voorwaarde]
    Stap_289[Stap]
    1234_290[1234]
    Stap_292[Stap]
    Voorwaarde_293[Voorwaarde]
    1234_294[1234]
    Voorwaarde_296[Voorwaarde]
    1234_297[1234]
    Stap_298[Stap]
    Open_M4_SVA_03_en_M4_SVA_04_300["Open M4_SVA_03 en M4_SVA_04"]
    1234_301[1234]
    Voorwaarde_302[Voorwaarde]
    M4_SVA03_en_M4_SVA04_zijn_open["M4_SVA03 en M4_SVA04 zijn open"]
    1234_305[1234]
    Stap_306[Stap]
    Start_M4_24["Start M4_24"]
    1234_309[1234]
    Voorwaarde_310[Voorwaarde]
    M4_24_draait["M4_24 draait"]
    1234_313[1234]
    Stap_314[Stap]
    Start_M4_25["Start M4_25"]
    1234_317[1234]
    Voorwaarde_318[Voorwaarde]
    M4_25_draait["M4_25 draait"]
    1234_321[1234]
    Stap_322[Stap]
    Start_M4_26["Start M4_26"]
    1234_325[1234]
    Voorwaarde_326[Voorwaarde]
    M4_26_draait["M4_26 draait"]
    1234_329[1234]
    Stap_330[Stap]
    Start_M4_27["Start M4_27"]
    1234_333[1234]
    Voorwaarde_334[Voorwaarde]
    M4_27_draait["M4_27 draait"]
    1234_337[1234]
    Stap_338[Stap]
    Start_M4_WHC23___Regeling_servoklep["Start M4_WHC23 - Regeling servoklep"]
    1234_341[1234]
    Voorwaarde_342[Voorwaarde]
    Geen_voorwaarde_344["Geen voorwaarde"]
    1234_345[1234]
    Stap_346[Stap]
    Start_M4_23["Start M4_23"]
    1234_349[1234]
    Voorwaarde_350[Voorwaarde]
    M4_23_draait["M4_23 draait"]
    1234_353[1234]
    Stap_354[Stap]
    Vergrendeling_op_M4_40_voor_2_seperatoren_aan["Vergrendeling op M4_40 voor 2 seperatoren aan"]
    1234_357[1234]
    Voorwaarde_358[Voorwaarde]
    Geen_voorwaarde_360["Geen voorwaarde"]
    1234_361[1234]
    Stap_362[Stap]
    Vergrendeling_op_M4_40_voor_2_seperatoren_uit["Vergrendeling op M4_40 voor 2 seperatoren uit"]
    1234_365[1234]
    Voorwaarde_366[Voorwaarde]
    M4_SVA_02_is_gesloten["M4_SVA_02 is gesloten"]
    1234_369[1234]
    Stap_370[Stap]
    Vergrendeling_van_M4_29_op_M4_02_inschakelen["Vergrendeling van M4_29 op M4_02 inschakelen"]
    1234_373[1234]
    Voorwaarde_374[Voorwaarde]
    M4_29_draait_376["M4_29 draait"]
    1234_377[1234]
    Voorwaarde_378[Voorwaarde]
    M4_BN1_en_M4_BN2_en_AW0__Aanloopweerstand_OK__of_M4_32_draait["M4_BN1 en M4_BN2 en AW0 (Aanloopweerstand OK) of M4_32 draait"]
    1234_381[1234]
    Stap_382[Stap]
    Start_M4_32_Hoofdmotor["Start M4_32 Hoofdmotor"]
    1234_385[1234]
    Voorwaarde_386[Voorwaarde]
    M4_32_draait["M4_32 draait"]
    1234_389[1234]
    390[390]
    392[392]
    1234_393[1234]
    394[394]
    Stap_396[Stap]
    1234_397[1234]
    Open_M4_SVA912["Open M4_SVA912"]
    Voorwaarde_400[Voorwaarde]
    1234_401[1234]
    M4_SVA912_is_open["M4_SVA912 is open"]
    Stap_404[Stap]
    1234_405[1234]
    Stop_ASP["Stop ASP"]
    Voorwaarde_408[Voorwaarde]
    1234_409[1234]
    Geen_voorwaarde_410["Geen voorwaarde"]
    420[420]
    422[422]
    492[492]
    Start_M4_32_4_en_M4_32_5["Start M4_32_4 en M4_32_5"]
    M4_32_4_en_M4_32_5_draaien["M4_32_4 en M4_32_5 draaien"]
    Start_M4_32_10_en_M4_32_12["Start M4_32_10 en M4_32_12"]
    M4_32_10_en_M4_32_12_draaien["M4_32_10 en M4_32_12 draaien"]
    Controlestap[Controlestap]
    Hulpmotor[Hulpmotor]
    Start_M4_32_14_Koelventilator_hoofdmotor["Start M4_32_14 Koelventilator hoofdmotor"]
    M4_32_14_draait["M4_32_14 draait"]
    Start_M4_53["Start M4_53"]
    M4_53_draait["M4_53 draait"]
    Start_M4_54["Start M4_54"]
    M4_54_draait["M4_54 draait"]
    Start_M4_16["Start M4_16"]
    M4_16_draait["M4_16 draait"]
    Start_M4_20["Start M4_20"]
    M4_20_draait["M4_20 draait"]
    Start_M4_21["Start M4_21"]
    M4_21_draait["M4_21 draait"]
    Start_M4_22["Start M4_22"]
    M4_22_draait["M4_22 draait"]
    Keuzestap[Keuzestap]
    Keuze_Sep1___Sep2["Keuze Sep1 + Sep2"]
    Keuze_enkel_Sep2["Keuze enkel Sep2"]
    Start_M4_39["Start M4_39"]
    M4_39_draait["M4_39 draait"]
    Start_M4_51["Start M4_51"]
    M4_51_draait["M4_51 draait"]
    Start_M4_52["Start M4_52"]
    M4_52_draait["M4_52 draait"]
    Start_M4_15["Start M4_15"]
    M4_15_draait["M4_15 draait"]
    Start_M4_17["Start M4_17"]
    M4_17_draait["M4_17 draait"]
    Start_M4_18["Start M4_18"]
    M4_18_draait["M4_18 draait"]
    Start_M4_19["Start M4_19"]
    M4_19_draait["M4_19 draait"]
    Open_M4_SVA_02["Open M4_SVA_02"]
    M4_SVA_02_is_open["M4_SVA_02 is open"]
    Start_M4_40["Start M4_40"]
    M4_40_draait["M4_40 draait"]
    Sluit_M4_SVA_02["Sluit M4_SVA_02"]
    M4_SVA_02_is_gesloten_287["M4_SVA_02 is gesloten"]
    Stop_M4_19__M4_18__M4_17__M4_15__M4_52__M4_51__M4_39["Stop M4_19, M4_18, M4_17, M4_15, M4_52, M4_51, M4_39"]
    Geen_voorwaarde_295["Geen voorwaarde"]
    1234_299[1234]
    1234_303[1234]
    1234_307[1234]
    1234_311[1234]
    1234_315[1234]
    1234_319[1234]
    1234_323[1234]
    1234_327[1234]
    1234_331[1234]
    1234_335[1234]
    1234_339[1234]
    1234_343[1234]
    1234_347[1234]
    1234_351[1234]
    1234_355[1234]
    1234_359[1234]
    1234_363[1234]
    1234_367[1234]
    1234_371[1234]
    1234_375[1234]
    1234_379[1234]
    1234_383[1234]
    1234_387[1234]
    462[462]
    4[4]
    5[5]
    Hoofd_Sequentie_M4["Hoofd Sequentie M4"]
    Date_[Date:]
    _200_[<200>]
    Designer_[Designer:]
    Tonny_Lemmens["Tonny Lemmens"]
    3___3["3 / 3"]
    Page_[Page:]
    87[87]
    15[15]
    Stap_19[Stap]
    Voorwaarde_23[Voorwaarde]
    Stap_27[Stap]
    Voorwaarde_31[Voorwaarde]
    Stap_35[Stap]
    Voorwaarde_39[Voorwaarde]
    Stap_43[Stap]
    Voorwaarde_47[Voorwaarde]
    Stap_51[Stap]
    Voorwaarde_55[Voorwaarde]
    Stap_59[Stap]
    Voorwaarde_63[Voorwaarde]
    Stap_67[Stap]
    Voorwaarde_71[Voorwaarde]
    Stap_75[Stap]
    Voorwaarde_79[Voorwaarde]
    Stap_83[Stap]
    1234_375 --> 1234_307
    1234_347 --> 1234_359
    1234_315 --> 1234_319
    1234_303 --> Start_M4_21
    Start_M4_17 --> M4_17_draait
    Keuze_Sep1___Sep2 --> M4_39_draait
    Stap_19 --> Voorwaarde_23
    Date_ --> 420
    Date_ --> 422
    Stap_35 --> Voorwaarde_39
    Stap_67 --> Voorwaarde_71
    M4_32_4_en_M4_32_5_draaien --> Start_M4_32_10_en_M4_32_12
    1234_323 --> Hulpmotor
    Controlestap --> M4_54_draait
    1234_383 --> M4_52_draait
    Start_M4_52 --> 1234_387
    1234_379 --> 1234_383
    Start_M4_18 --> 1234_327
    1234_371 --> 1234_375
    1234_363 --> 1234_367
    1234_367 --> 1234_371
    1234_359 --> 1234_363
    1234_355 --> 1234_343
    1234_351 --> 1234_355
    1234_339 --> 1234_351
    1234_343 --> 1234_347
    1234_331 --> 1234_335
    1234_335 --> 1234_339
    1234_307 --> 1234_311
    1234_319 --> 1234_323
    1234_311 --> 1234_315
    1234_299 --> 1234_303
    Geen_voorwaarde_295 --> 1234_299
    Stop_M4_19__M4_18__M4_17__M4_15__M4_52__M4_51__M4_39 --> Geen_voorwaarde_295
    M4_SVA_02_is_gesloten_287 --> Stop_M4_19__M4_18__M4_17__M4_15__M4_52__M4_51__M4_39
    Sluit_M4_SVA_02 --> Start_M4_21
    M4_40_draait --> M4_SVA_02_is_gesloten_287
    M4_40_draait --> Sluit_M4_SVA_02
    Start_M4_40 --> Keuzestap
    M4_SVA_02_is_open --> Start_M4_40
    M4_22_draait --> M4_SVA_02_is_open
    Open_M4_SVA_02 --> Start_M4_22
    Start_M4_19 --> M4_19_draait
    M4_19_draait --> Open_M4_SVA_02
    M4_18_draait --> Start_M4_19
    M4_17_draait --> Start_M4_18
    Start_M4_15 --> M4_15_draait
    M4_15_draait --> Start_M4_17
    M4_52_draait --> Start_M4_15
    M4_16_draait --> Keuze_enkel_Sep2
    Start_M4_16 --> Start_M4_20
    Start_M4_51 --> M4_51_draait
    M4_51_draait --> Start_M4_52
    M4_39_draait --> Start_M4_51
    Start_M4_39 --> M4_40_draait
    Keuze_enkel_Sep2 --> Start_M4_39
    Keuzestap --> Keuze_Sep1___Sep2
    M4_21_draait --> M4_18_draait
    Start_M4_22 --> M4_22_draait
    M4_20_draait --> M4_40_draait
    Start_M4_21 --> M4_21_draait
    Start_M4_20 --> M4_20_draait
    M4_54_draait --> M4_16_draait
    M4_54_draait --> Start_M4_16
    Stap_83 --> M4_53_draait
    M4_53_draait --> Start_M4_54
    Start_M4_53 --> Start_M4_32_4_en_M4_32_5
    M4_32_14_draait --> Start_M4_53
    Hulpmotor --> Start_M4_32_14_Koelventilator_hoofdmotor
    Voorwaarde_23 --> Stap_27
    15 --> Stap_19
    Tonny_Lemmens --> 492
    Voorwaarde_31 --> Stap_35
    Stap_27 --> Voorwaarde_31
    Voorwaarde_39 --> Stap_43
    Voorwaarde_47 --> Stap_51
    Stap_43 --> Voorwaarde_47
    Voorwaarde_55 --> Stap_59
    Stap_51 --> Voorwaarde_55
    Voorwaarde_63 --> Stap_67
    Stap_59 --> Voorwaarde_63
    Voorwaarde_71 --> Stap_75
    Voorwaarde_79 --> Stap_83
    Stap_75 --> Voorwaarde_79
    Start_M4_54 --> 87
    Start_M4_32_4_en_M4_32_5 --> M4_32_4_en_M4_32_5_draaien
    Start_M4_32_10_en_M4_32_12 --> M4_32_10_en_M4_32_12_draaien
    Start_M4_32_14_Koelventilator_hoofdmotor --> Start_M4_32_10_en_M4_32_12
    Stap_192 --> Stap_83
    Date_ --> 390
    Date_ --> 392
    Voorwaarde_144 --> 1234_381
    1234_381 --> 1234_385
    Stap_140 --> Voorwaarde_144
    Voorwaarde_132 --> 1234_377
    1234_369 --> 1234_373
    1234_365 --> Stap_280
    1234_361 --> 1234_365
    Voorwaarde_268 --> 1234_353
    1234_353 --> 1234_357
    1234_349 --> Voorwaarde_196
    Voorwaarde_296 --> 1234_297
    1234_341 --> 1234_345
    1234_333 --> 1234_337
    1234_325 --> 1234_329
    1234_317 --> 1234_321
    1234_309 --> 1234_313
    1234_301 --> 1234_305
    1234_345 --> 1234_349
    1234_337 --> 1234_341
    1234_329 --> 1234_333
    1234_321 --> 1234_325
    1234_313 --> 1234_317
    1234_305 --> 1234_309
    1234_297 --> 1234_301
    Stap_292 --> Stap_272
    Voorwaarde_288 --> Stap_292
    Voorwaarde_284 --> Voorwaarde_288
    Stap_280 --> Voorwaarde_284
    Voorwaarde_260 --> Stap_264
    Voorwaarde_244 --> Stap_248
    Voorwaarde_204 --> 1234_361
    1234_357 --> Stap_272
    Stap_272 --> Voorwaarde_276
    Stap_264 --> Voorwaarde_268
    Voorwaarde_252 --> Stap_256
    Stap_256 --> Voorwaarde_260
    Stap_248 --> Voorwaarde_252
    Voorwaarde_228 --> Stap_232
    Voorwaarde_236 --> Stap_240
    Stap_240 --> Voorwaarde_244
    Stap_232 --> Voorwaarde_236
    Voorwaarde_220 --> Stap_224
    Stap_224 --> Voorwaarde_228
    Voorwaarde_212 --> Stap_216
    Stap_216 --> Voorwaarde_220
    Stap_200 --> Stap_208
    Stap_208 --> Voorwaarde_212
    Voorwaarde_196 --> Voorwaarde_204
    Voorwaarde_196 --> Stap_200
    Voorwaarde_276 --> Stap_148
    Stap_184 --> Voorwaarde_188
    Voorwaarde_188 --> Stap_192
    Voorwaarde_168 --> Voorwaarde_172
    Stap_176 --> Voorwaarde_180
    Voorwaarde_180 --> Stap_184
    Voorwaarde_172 --> Stap_176
    Voorwaarde_152 --> Stap_156
    Voorwaarde_160 --> Stap_164
    Stap_164 --> Voorwaarde_168
    Stap_156 --> Voorwaarde_160
    Stap_148 --> Voorwaarde_152
    87 --> 1234_369
    Tonny_Lemmens --> 462
    Voorwaarde_116 --> Stap_120
    Voorwaarde_124 --> Stap_128
    Stap_120 --> Voorwaarde_124
    Voorwaarde_132 --> Voorwaarde_136
    Stap_128 --> Voorwaarde_132
    1234_377 --> Stap_140
    Voorwaarde_136 --> Voorwaarde_79
    1234_385 --> Voorwaarde_23
    15 --> Stap_19
    Voorwaarde_23 --> Stap_27
    Voorwaarde_31 --> Stap_35
    Stap_27 --> Voorwaarde_31
    Voorwaarde_39 --> Stap_43
    Stap_35 --> Voorwaarde_39
    Voorwaarde_47 --> Stap_51
    Stap_43 --> Voorwaarde_47
    Voorwaarde_55 --> Stap_59
    Stap_51 --> Voorwaarde_55
    Voorwaarde_63 --> Stap_67
    Stap_59 --> Voorwaarde_63
    Stap_67 --> Voorwaarde_71
    Voorwaarde_71 --> Stap_75
    Stap_75 --> Voorwaarde_79
    Stap_83 --> 87
    Date_ --> 87
    Designer_ --> 89
    Designer_ --> 104
    Page_ --> 106
    Geen_voorwaarde_78 --> Productiestap
    M4_36_draait --> Start_M4_TOIC1__tonnage__regeling_weegband_
    Start_M4_TOIC1__tonnage__regeling_weegband_ --> Geen_voorwaarde_78
    M4_35_draait --> Start_M4_36
    Start_M4_36 --> M4_36_draait
    M4_34B_draait --> Start_M4_35
    Start_M4_35 --> M4_35_draait
    M4_34A_draait --> Start_M4_34B
    Start_M4_34B --> M4_34B_draait
    M4_33_draait --> Start_M4_34A
    Start_M4_34A --> M4_34A_draait
    M4_SVA_03_en_M4_SVA_04_zijn_open --> Start_M4_33
    Start_M4_33 --> M4_33_draait
    M4_30_draait --> Open_M4_SVA_03_en_M4_SVA_04
    Start_M4_30 --> M4_30_draait
    Open_M4_SVA_03_en_M4_SVA_04 --> M4_SVA_03_en_M4_SVA_04_zijn_open